# 插值

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
import scipy as sc

设置 Numpy 浮点数显示格式

In [2]:
np.set_printoptions(precision=2, suppress=True)

### 一维插值 - interp1d()

In [7]:
from scipy.interpolate import interp1d

In [8]:
xs = np.arange(10)
ys = 2*xs + 1

In [9]:
print(xs)
print(ys)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]


In [10]:
interp_func = interp1d(xs, ys)

In [11]:
newarr = interp_func(np.arange(2.1, 3, 0.1))
newarr

array([5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8])

### 单变量插值 - UnivariateSpline

在一维插值中，点是针对单个曲线拟合的，而在样条插值中，点是针对使用多项式分段定义的函数拟合的

In [12]:
from scipy.interpolate import UnivariateSpline

In [13]:
xs = np.arange(10)
ys = xs ** 2 + np.sin(xs) + 1   

In [14]:
# 生成一个插值函数
interp_func = UnivariateSpline(xs, ys)

In [15]:
newarr = interp_func(np.arange(2.1, 3, 0.1))
newarr

array([5.63, 6.04, 6.47, 6.92, 7.39, 7.89, 8.4 , 8.93, 9.48])

### 径向基函数插值 - Rbf()

径向基函数是对应于固定参考点定义的函数

In [16]:
from scipy.interpolate import Rbf

In [17]:
xs = np.arange(10)
ys = xs ** 2 + np.sin(xs) + 1

In [18]:
interp_func = Rbf(xs, ys)
newarr = interp_func(np.arange(2.1, 3, 0.1))

In [19]:
newarr

array([6.26, 6.62, 7.  , 7.4 , 7.82, 8.25, 8.7 , 9.16, 9.64])