# 数组属性

### 基本属性

In [2]:
from numpy import *

In [3]:
a = array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

数组元素属性

In [4]:
a.dtype

dtype('int32')

数组形状

In [5]:
a.shape

(2, 4)

元素数目

In [7]:
a.size

8

元素所占字节大小

In [8]:
a.itemsize

4

所有元素所占字节

In [9]:
a.nbytes

32

数据维度

In [10]:
a.ndim

2

### 形状相关

In [11]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]


将所有元素组成一维数组，按行排列

In [15]:
# flatten 是复制操作，后续操作不会影响到原始数据
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
# ravel 是引用操作，修改数据会影响到前面的数据
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

重新修改形状

In [16]:
a.shape = 4,2
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [17]:
a.resize(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

交换两个轴的顺序

In [24]:
a.swapaxes(1, 0)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

转置

In [25]:
a.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

删除长度为1的维度

In [28]:
a.squeeze()

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### 填充复制

In [29]:
b = a.copy()
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

复制不会影响原始数组

In [30]:
b[1][-1] = 8
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 8]])

以指定元素填充数组

In [32]:
b.fill(9)
b

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

### 转化

转化为列表

In [34]:
a.tolist()

[[0, 1, 2, 3], [4, 5, 6, 7]]

转化为字符串

In [35]:
a.tostring()

C:\Users\Miracle\AppData\Local\Temp\ipykernel_372\3114260871.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  a.tostring()


b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00'

修改数组元素的类型

In [37]:
print(a.dtype)
a = a.astype(float32)
print(a.dtype)

int32
float32


### 查找排序

非零元素的索引

In [38]:
a.nonzero()

(array([0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3], dtype=int64))

### 元素数学操作

限制在一定范围

In [41]:
a = array([
    [4, 1, 3],
    [2, 1, 5]
])
a.clip(0,2)

array([[2, 1, 2],
       [2, 1, 2]])