# 矩阵

使用 mat 方法可以将二维数组转换成矩阵

In [1]:
import numpy as np

In [2]:
a = np.array([
    [1, 2, 4],
    [2, 5, 3],
    [7, 8, 9]
])

In [3]:
A = np.mat(a)

In [4]:
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [6]:
B = np.mat("1,2,3,4,5,6,7,8,9")
B

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

利用分块创造新的矩阵

In [8]:
a = np.array([
    [1, 2],
    [3, 4]
])
b = np.array([
    [10, 20],
    [30, 40]
])
np.bmat("a,b;b,a")

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

矩阵与向量的乘法

In [9]:
x = np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

In [10]:
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [11]:
A * x

matrix([[17],
        [21],
        [50]])