# 数组二元运算

In [1]:
import numpy as np

### 四则运算

In [2]:
a = np.array([1, 2])

In [3]:
a * 3

array([3, 6])

数组逐元素相乘

In [4]:
a = np.array([1, 2])
b = np.array([3, 4])
a * b

array([3, 8])

使用函数

In [5]:
np.multiply(a, b)

array([3, 8])

multiply 函数可以将结果存入第三个参数

In [11]:
c = np.zeros(a.shape, a.dtype)
np.multiply(a, b, c)
print(a)
print(b)
print(c)

[1 2]
[3 4]
[3 8]


### 比较和逻辑运算

等于操作也是逐元素比较的

In [12]:
a = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5]
])
b = np.array([
    [1, 2, 5, 4],
    [1, 3, 4, 5]
])
a == b

array([[ True,  True, False,  True],
       [False,  True,  True,  True]])

如果要判断两个数组是否完全一样，需要使用 all(a == b)

In [15]:
np.all(a == b)

False

逻辑与操作 （logical_and），也是逐元素的与操作

In [16]:
a = np.array([0, 1, 2])
b = np.array([0, 10, 0])
np.logical_and(a, b)

array([False,  True, False])

按位取反

In [17]:
from numpy import uint8

a = np.array([1, 2, 3, 4], dtype=uint8)
print(a)
print(~a)

[1 2 3 4]
[254 253 252 251]
