# 通用方法

In [2]:
import numpy as np

In [3]:
a = np.array([0, 1, 2])
b = np.array([2, 3, 4])

np.add(a, b)

array([2, 4, 6])

In [4]:
dir(np.add)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_get_strided_loop',
 '_resolve_dtypes_and_context',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'resolve_dtypes',
 'signature',
 'types']

### reduce 方法

add.reduce(a)
将 op 沿着某个轴应用，使得数组 a 的维数降低一维
如果作用到一维数组，即为求和

In [5]:
a = np.array([1, 2, 3, 4])
a.shape

(4,)

In [6]:
np.add.reduce(a)

10

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]])
np.add.reduce(b)

array([5, 7, 9])

指定维度

In [8]:
np.add.reduce(b, 1)

array([ 6, 15])

In [9]:
np.add.reduce(b, 0)

array([5, 7, 9])

In [10]:
np.add.reduce(b, 2)

AxisError: axis 2 is out of bounds for array of dimension 2

也可作用于字符串

In [12]:
c = np.array(["ab", "cd", "ef"], np.object)
np.add.reduce(c)

C:\Users\Miracle\AppData\Local\Temp\ipykernel_22900\2988310588.py:1: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  c = np.array(["ab", "cd", "ef"], np.object)


AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### accumulate 方法

add.accumulate(a)
可以看成保存 reduce 每一步的结果所形成的数组

In [13]:
a = np.array([1, 2, 3, 4])
np.add.accumulate(a)

array([ 1,  3,  6, 10])

In [14]:
b = np.array([1, 1, 0, 1])
np.logical_and.accumulate(b)

array([ True,  True, False, False])

### reduceat 方法

add.reduceat(a, indices) 将操作符运用到指定的下标，返回一个与indices大小相同的数组

In [15]:
a = np.array([0, 10, 20, 30, 40, 50])
indices = np.array([1, 4])
np.add.reduceat(a, indices)

array([60, 90])

60 表示从下标 1（20）加到下标 3 的结果【10,20,30】
90 表示从下标 4（40）加到结束【40,50】

### outer 方法

add.outer(a, b)

对于a中每个元素，将add运用到它和b的每一个元素所得到的结果

In [16]:
a = np.array([0, 1])
b = np.array([1, 2, 3])
np.add.outer(a, b)

array([[1, 2, 3],
       [2, 3, 4]])