# 数组类型

### 复数数组

In [1]:
from numpy import *

生成一个复数数组

In [2]:
a = array([1+1j, 2 ,3 ,4])
a

array([1.+1.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [3]:
a.dtype

dtype('complex128')

数组的实部 - real

In [4]:
a.real

array([1., 2., 3., 4.])

数组的虚部 - imag

In [5]:
a.imag

array([1., 0., 0., 0.])

设置实部、虚部

In [6]:
a.real = [2, 3, 4, 5]
a.imag = [6, 7, 8 ,9]
a

array([2.+6.j, 3.+7.j, 4.+8.j, 5.+9.j])

### 类型转换

In [7]:
a = array([1.5, -3], dtype=float32)
a

array([ 1.5, -3. ], dtype=float32)

asarray 函数，不会改变原数组的值

In [12]:
b = asarray(a, dtype=float64)
print(b)

[ 1.5 -3. ]


In [13]:
print(a.dtype)
print(b.dtype)

float32
float64


astype 方法，返回一个新数组，也不会改变原来的值

In [15]:
print(a.dtype)
a.astype(float64)
print(a.dtype)

float32
float32


### view 方法

In [16]:
a = array([1,2,3,4],dtype=int32)
a

array([1, 2, 3, 4])

view 会将 a 在内存中的表示看成 uint8 进行解析

In [17]:
b = a.view(uint8)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)

修改 a 会修改 b 的内存，因为共用一块内存

In [21]:
a[0] = 2*30
print(a)
print(b)

[60  2  3  4]
[60  0  0  0  2  0  0  0  3  0  0  0  4  0  0  0]
