# 数组排序

In [2]:
%pylab

Using matplotlib backend: TkAgg
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


### sort 函数 - 不改变原数组

In [3]:
names = array(["bob","sue","jan","ad"])
weights = array([20.8, 93.2, 53.4,61.8])
sort(weights)

array([20.8, 53.4, 61.8, 93.2])

### argsort 函数 - 返回从小到大的排列在数组中的索引位置

In [5]:
ordered_indices = argsort(weights)
ordered_indices

array([0, 2, 3, 1], dtype=int64)

可以用来进行索引

In [6]:
weights[ordered_indices]

array([20.8, 53.4, 61.8, 93.2])

### sort 和 argsort 方法

argsort 不会改变原数组

In [7]:
data = array([20.8, 93.2, 53.4, 61.8])
data.argsort()

array([0, 2, 3, 1], dtype=int64)

sort 会改变原数组

In [8]:
data.sort()
data

array([20.8, 53.4, 61.8, 93.2])

### 二维数组排序

对于多维数组，sort方法默认沿着最后一维(最里面一维)开始排序

In [2]:
a = array([
    [0.2,0.1,0.5],
    [0.4,0.8,0.3],
    [0.9,0.6,0.7]
])

In [3]:
sort(a)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

In [5]:
sort(a, axis=0) # 按列

array([[0.2, 0.1, 0.3],
       [0.4, 0.6, 0.5],
       [0.9, 0.8, 0.7]])

In [6]:
sort(a, axis=1) # 按行

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

### searchsorted 函数 - 给出values应该插入的位置

In [3]:
sorted_array = linspace(0,1,5)
sorted_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
values = array([0.1, 0.8, 0.3, 0.12, 0.5, 0.25])
searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1], dtype=int64)

In [6]:
from numpy.random import rand
data = rand(100)
data

array([0.29980909, 0.36008563, 0.24265199, 0.51597201, 0.3952751 ,
       0.65647723, 0.74733878, 0.31098364, 0.31032866, 0.00112556,
       0.67206116, 0.07058655, 0.11357561, 0.24776087, 0.59777043,
       0.061289  , 0.69113886, 0.93654528, 0.23254124, 0.45725707,
       0.60009949, 0.67604215, 0.02518567, 0.22471124, 0.16389223,
       0.92589566, 0.27654398, 0.2593047 , 0.39109351, 0.59221449,
       0.39929507, 0.56712471, 0.16451825, 0.9982863 , 0.42271738,
       0.49437078, 0.45199726, 0.91595815, 0.70115604, 0.98454563,
       0.49202113, 0.67674827, 0.90071232, 0.86717894, 0.47323312,
       0.91352321, 0.55253576, 0.52329713, 0.57515849, 0.75565502,
       0.75933466, 0.2805349 , 0.48157852, 0.89455396, 0.25383651,
       0.07974397, 0.72150527, 0.26798467, 0.50265862, 0.82892378,
       0.888607  , 0.48940447, 0.72456575, 0.00559278, 0.98651953,
       0.82055996, 0.66497111, 0.18943745, 0.62592909, 0.70501687,
       0.0221641 , 0.74771132, 0.89188637, 0.99796125, 0.40093

In [7]:
data.sort()

In [8]:
data

array([0.00112556, 0.00120907, 0.00559278, 0.0221641 , 0.02518567,
       0.061289  , 0.07058655, 0.07974397, 0.11357561, 0.11368385,
       0.16389223, 0.16451825, 0.18943745, 0.21178106, 0.22471124,
       0.23254124, 0.24265199, 0.24521649, 0.24776087, 0.25383651,
       0.2593047 , 0.26798467, 0.27654398, 0.2805349 , 0.28075139,
       0.29980909, 0.31032866, 0.31098364, 0.32854481, 0.35889227,
       0.36008563, 0.38005578, 0.39109351, 0.3952751 , 0.39929507,
       0.40093311, 0.40556007, 0.41597562, 0.42271738, 0.44725593,
       0.45199726, 0.45725707, 0.47323312, 0.48157852, 0.48940447,
       0.49202113, 0.49303672, 0.49437078, 0.49698938, 0.50265862,
       0.51597201, 0.52329713, 0.53375964, 0.55253576, 0.55451244,
       0.56712471, 0.57515849, 0.59221449, 0.59777043, 0.60009949,
       0.60619076, 0.60995727, 0.62592909, 0.64231247, 0.65647723,
       0.66497111, 0.66523166, 0.67206116, 0.67604215, 0.67674827,
       0.68465178, 0.69113886, 0.70115604, 0.70501687, 0.72019

不加括号，默认是元组

In [9]:
bounds = .4, .6
bounds

(0.4, 0.6)

In [10]:
low_idx, high_idx = searchsorted(data, bounds)
print(low_idx)
print(high_idx)

35
59


In [11]:
data[low_idx:high_idx]

array([0.40093311, 0.40556007, 0.41597562, 0.42271738, 0.44725593,
       0.45199726, 0.45725707, 0.47323312, 0.48157852, 0.48940447,
       0.49202113, 0.49303672, 0.49437078, 0.49698938, 0.50265862,
       0.51597201, 0.52329713, 0.53375964, 0.55253576, 0.55451244,
       0.56712471, 0.57515849, 0.59221449, 0.59777043])