# 数组形状

In [10]:
%pylab

Using matplotlib backend: TkAgg
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


### 修改数组的形状 

直接修改数组的 shape

In [15]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [16]:
a.shape = (2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

使用 reshape 方法，不过此方法不会修改原数据，而是返回一个新的数组

In [17]:
b = arange(8)
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
c = b.reshape(4, 2)
print(b.shape)
print(c.shape)

(8,)
(4, 2)


### 使用 newaxis 增加数组维数

In [19]:
a = arange(3)
print(shape(a))
print(a.shape)

(3,)
(3,)


In [20]:
y = a[newaxis, :]
shape(y)

(1, 3)

根据插入位置的不同，可以返回不同形状的数组

In [21]:
z = a[:, newaxis]
shape(z)

(3, 1)

插入多个新维度

In [22]:
z = a[newaxis, newaxis, :]
z.shape

(1, 1, 3)

### 使用 squeeze 方法去除多余的轴，对数组进行展开[返回一个将所有长度为1的维度去除的新数组]

In [24]:
a = arange(6)
a.shape = (2,1,3)
b = a.squeeze()
b.shape

(2, 3)

### 数组转置 - 将所有维度反过来

In [26]:
a 

array([[[0, 1, 2]],

       [[3, 4, 5]]])

转置之后，行列交换，不会改变原数组

In [30]:
b = a.transpose()
print(a.shape, a)
print(b.shape, b)

(2, 1, 3) [[[0 1 2]]

 [[3 4 5]]]
(3, 1, 2) [[[0 3]]

 [[1 4]]

 [[2 5]]]


### 连接数组

In [3]:
x = array([
    [0,1,2],
    [10,11,12]
])
y = array([
    [50,51,52],
    [60,61,62]
])
print(x.shape)
print(y.shape)

(2, 3)
(2, 3)


默认按照第一维进行连接

In [4]:
z = concatenate((x, y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

选择按照第二维进行连接

In [5]:
z2 = concatenate((x,y), axis=1)
z2

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

Numpy 也提供了类似的函数，用于完成上述操作

In [9]:
from numpy import hstack, vstack


print(vstack((x,y)))

print(hstack((x,y)))

[[ 0  1  2]
 [10 11 12]
 [50 51 52]
 [60 61 62]]
[[ 0  1  2 50 51 52]
 [10 11 12 60 61 62]]


### flatten 数组

作用是将多维数组转化为一维数组

In [1]:
%pylab

Using matplotlib backend: TkAgg
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
a = array([[0,1],[2,3]])
b = a.flatten()
print(a)
print(b)

[[0 1]
 [2 3]]
[0 1 2 3]


返回的是数组的复制，改变 b 不会影响 a 的值

In [3]:
b[0] = 10
print(a)
print(b)

[[0 1]
 [2 3]]
[10  1  2  3]


### flat 属性

还可以使用数组自带的flat属性，返回一个迭代器

In [5]:
a.flat

In [6]:
b = a.flat
b[0]

0

修改 b 会修改 a

In [7]:
b[1] = 666
print(a)
print(b)

[[  0 666]
 [  2   3]]


### ravel 方法

In [8]:
a = array([[1,2],[3,4]])
b = a.ravel()
print(a)
print(b)

[[1 2]
 [3 4]]
[1 2 3 4]


修改 b 同样会修改 a

In [9]:
b[2] = 6
print(a)
print(b)

[[1 2]
 [6 4]]
[1 2 6 4]


### atleast_xd 函数 - 保证至少有 x 维

In [10]:
from numpy import atleast_1d


x = 1
atleast_1d(x)


array([1])