# 对角线 - diagonal

In [1]:
import numpy as np

In [2]:
a = np.array([11,21,31,12,22,32,13,23,33])
a.shape = 3,3
a

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

查看对角线元素

In [3]:
a.diagonal()

array([11, 22, 33])

使用偏移（offset）查看次对角线，正数表示右移，负数表示左移

In [4]:
a.diagonal(offset=1)

array([21, 32])

In [5]:
a.diagonal(offset=-1)

array([12, 23])

使用花式索引来得到对角线

In [6]:
i = [0, 1, 2]
a[i,i]

array([11, 22, 33])

修改对角线的值

In [7]:
a[i,i] = [66,77,88]
a

array([[66, 21, 31],
       [12, 77, 32],
       [13, 23, 88]])