# 数组方法

### 求和

In [1]:
%pylab

Using matplotlib backend: <object object at 0x000001CEE6F36C00>
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
a = array([[1,2,3],[4,5,6]])

求所有元素的和

In [3]:
sum(a)

21

按维度求和

In [4]:
sum(a,axis=0)

array([5, 7, 9])

In [5]:
sum(a,axis=1)

array([ 6, 15])

### 求积

求所有元素的乘积

In [6]:
a.prod()

720

### 求最大最小值

In [8]:
from numpy.random import rand
# 3 行 4 列
a = rand(3, 4)
%precision 3
a

array([[0.456, 0.698, 0.941, 0.975],
       [0.341, 0.964, 0.247, 0.908],
       [0.022, 0.52 , 0.5  , 0.485]])

全局最小

In [11]:
a.min()

0.022

沿着某个轴的最小 - axis 0 表示每列，axis 1 表示每行

In [12]:
a.min(axis=0)

array([0.022, 0.52 , 0.247, 0.485])

In [13]:
a.min(axis=1)

array([0.456, 0.247, 0.022])

全局最大

In [14]:
a.max()

0.975

沿着某个轴的最大 - axis 0 表示每列，axis 1 表示每行

In [15]:
a.max(axis=0)

array([0.456, 0.964, 0.941, 0.975])

In [16]:
a.max(axis=1)

array([0.975, 0.964, 0.52 ])

最大最小值的位置 - argmin , argmax

In [17]:
a.argmin()

8

In [18]:
a.argmin(axis=0)

array([2, 2, 1, 2], dtype=int64)

### 均值

使用 mean 方法

In [26]:
a = array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [27]:
a.mean()

6.500

In [28]:
a.mean(axis=0)

array([5.5, 6.5, 7.5])

In [29]:
a.mean(axis=1)

array([ 2.,  5.,  8., 11.])

使用 mean 函数

In [30]:
mean(a)

6.500

使用 average 函数

In [31]:
average(a)

6.500

In [32]:
average(a, axis=0)

array([5.5, 6.5, 7.5])

In [33]:
average(a, axis=1)

array([ 2.,  5.,  8., 11.])

### clip 方法

将数值限制在某个范围 - clip(x,y) 小于 x 的变成 x, 大于 y 的变成 y

In [35]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### ptp 方法

计算最大值和最小值之差

In [38]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
a.ptp()

11

### round 方法，取近似值，默认到整数

In [42]:
a = array([1.251,2.567,3.489])
a.round()

array([1., 3., 3.])

In [43]:
# 近似到两位小数
a.round(decimals=2)

array([1.25, 2.57, 3.49])