# 数组排序

In [1]:
%pylab

Using matplotlib backend: <object object at 0x000001A8F9A7DC10>
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


### sort 函数 - 不改变原数组

In [3]:
names = array(["bob","sue","jan","ad"])
weights = array([20.8, 93.2, 53.4,61.8])
sort(weights)

array([20.8, 53.4, 61.8, 93.2])

### argsort 函数 - 返回从小到大的排列在数组中的索引位置

In [5]:
ordered_indices = argsort(weights)
ordered_indices

array([0, 2, 3, 1], dtype=int64)

可以用来进行索引

In [6]:
weights[ordered_indices]

array([20.8, 53.4, 61.8, 93.2])

### sort 和 argsort 方法

argsort 不会改变原数组

In [7]:
data = array([20.8, 93.2, 53.4, 61.8])
data.argsort()

array([0, 2, 3, 1], dtype=int64)

sort 会改变原数组

In [8]:
data.sort()
data

array([20.8, 53.4, 61.8, 93.2])

### 二维数组排序

对于多维数组，sort方法默认沿着最后一维开始排序

In [ ]:
a = array