# 数组类型

### 复数数组

In [1]:
from numpy import *

生成一个复数数组

In [4]:
a = array([1+1j, 2 ,3 ,4])
a

array([1.+1.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [6]:
a.dtype

dtype('complex128')

数组的实部 - real

In [8]:
a.real

array([1., 2., 3., 4.])

数组的虚部 - imag

In [9]:
a.imag

array([1., 0., 0., 0.])

设置实部、虚部

In [10]:
a.real = [2, 3, 4, 5]
a.imag = [6, 7, 8 ,9]
a

array([2.+6.j, 3.+7.j, 4.+8.j, 5.+9.j])