# Numpy 数组及其索引

In [1]:
from numpy import *

### 产生数组

产生数组方式 - 从列表产生数组

In [2]:
lst = [0, 1, 2, 3]
a = array(lst)
a

array([0, 1, 2, 3])

产生数组方式 - 直接从列表传入

In [3]:
a = array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

### 数组属性

查看类型

In [4]:
type(a)

numpy.ndarray

查看数组中的数据类型

In [5]:
a.dtype

dtype('int32')

查看每个元素所占的字节

In [6]:
a.itemsize

4

查看形状，会返回一个元组，每个元素代表该维的元素数目

In [7]:
a.shape

(4,)

### 使用 fill 方法设定初值

In [10]:
a.fill(6)
a

array([6, 6, 6, 6])

### 多维数组及其属性

In [11]:
b = array(
    [
        [0,1,2,3],
        [10,11,12,13]
    ]
)

查看数组维度 - ndim

In [14]:
b.ndim

2

查看数组形状 - shape

In [12]:
b.shape

(2, 4)

查看数组总的元素个数 - size

In [13]:
b.size

8

多维数组切片 - 切片是引用

In [17]:
a

array([6, 6, 6, 6])

In [18]:
b = a[1:3]
b

array([6, 6])

In [19]:
b[1] = 3
print(a)
print(b)

[6 6 3 6]
[6 3]


### where 语句

一维数组

In [20]:
c = array([0, 12, 5, 20])

判断数组中元素是否大于10

In [21]:
c > 10

array([False,  True, False,  True])