# 学习 PyTorch-Day1


In [1]:
import torch
import numpy as np

# 指认到M1芯片
device = torch.device("mps")

## 初始化一个 Tensor


- 直接从数据初始化


In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

- 直接从 Numpy 数组转换


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

- 从另一个 Tensor 转换(将会与该 Tensor 在 shape 以及 datatype 上保持一致)


In [4]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)  # 使用x_data的shape，被重新给定了datashape(float)
x_rand

tensor([[0.7071, 0.8706],
        [0.0495, 0.8279]])

- 使用一个随机量或者一个常量

In [6]:
shape = (2, 3)  # 表示Tensor的维度信息

rand_tensor = torch.rand(shape)  # 使用给定shape初始化一个Tensor，值全为1
print(rand_tensor)

ones_tensor = torch.ones(shape)  # 使用给定shape初始化一个Tensor，值全部随机
print(ones_tensor)

zeros_tensor = torch.zeros(shape)  # 使用给定shape初始化一个Tensor，值全为0
print(zeros_tensor)

tensor([[0.2366, 0.8939, 0.5052],
        [0.6590, 0.4327, 0.1667]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor的属性

Tensor的属性包括且不限于如下：

1. shape 【尺寸】
2. dtype 【数据类型】
3. device 【存储设备】

In [7]:
t = torch.rand(3, 4, device=device)
print("Shape of tensor: {}".format(t.shape))
print("Datatype of tensor: {}".format(t.dtype))
print("Device of tensor: {}".format(t.device))

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: mps:0


## Tensor 运算

- to method

In [8]:
# Tensor默认是分配在CPU上，如果我们有GPU可以使用，应该使用 to 方法将Tensor转到GPU上
# if torch.cuda.is_available():
tensor = torch.rand((3,2))
if torch.backends.mps.is_available():
    tensor = tensor.to("mps")
tensor

/opt/anaconda3/envs/ml/lib/python3.7/site-packages/torch/_tensor_str.py:103: UserWarning: The operator 'aten::bitwise_and.Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484744261/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))


tensor([[0.3961, 0.5199],
        [0.9822, 0.7936],
        [0.2551, 0.8512]], device='mps:0')

- 类似于Numpy的索引和切片

In [9]:
tensor = torch.randn(4, 4)
print(tensor)
print("First row of tensor: {}".format(tensor[0]))
print("First column of tensor: {}".format(tensor[:, 0]))
print("last column of tensor: {}".format(tensor[:, -1]))

tensor([[ 0.4111, -0.2422,  1.0655,  0.1739],
        [ 0.0115, -0.1728,  0.7108, -0.3837],
        [-0.0645, -0.9171,  0.5292,  2.6154],
        [ 0.0041, -0.0877,  0.2176, -0.7063]])
First row of tensor: tensor([ 0.4111, -0.2422,  1.0655,  0.1739])
First column of tensor: tensor([ 0.4111,  0.0115, -0.0645,  0.0041])
last column of tensor: tensor([ 0.1739, -0.3837,  2.6154, -0.7063])


- 拼接Tensor【torch.cat】

In [10]:
t1 = torch.cat([tensor,tensor,tensor], dim=0)
t1

tensor([[ 0.4111, -0.2422,  1.0655,  0.1739],
        [ 0.0115, -0.1728,  0.7108, -0.3837],
        [-0.0645, -0.9171,  0.5292,  2.6154],
        [ 0.0041, -0.0877,  0.2176, -0.7063],
        [ 0.4111, -0.2422,  1.0655,  0.1739],
        [ 0.0115, -0.1728,  0.7108, -0.3837],
        [-0.0645, -0.9171,  0.5292,  2.6154],
        [ 0.0041, -0.0877,  0.2176, -0.7063],
        [ 0.4111, -0.2422,  1.0655,  0.1739],
        [ 0.0115, -0.1728,  0.7108, -0.3837],
        [-0.0645, -0.9171,  0.5292,  2.6154],
        [ 0.0041, -0.0877,  0.2176, -0.7063]])

In [11]:
t2 = torch.cat([tensor,tensor,tensor], dim=1)
t2

tensor([[ 0.4111, -0.2422,  1.0655,  0.1739,  0.4111, -0.2422,  1.0655,  0.1739,
          0.4111, -0.2422,  1.0655,  0.1739],
        [ 0.0115, -0.1728,  0.7108, -0.3837,  0.0115, -0.1728,  0.7108, -0.3837,
          0.0115, -0.1728,  0.7108, -0.3837],
        [-0.0645, -0.9171,  0.5292,  2.6154, -0.0645, -0.9171,  0.5292,  2.6154,
         -0.0645, -0.9171,  0.5292,  2.6154],
        [ 0.0041, -0.0877,  0.2176, -0.7063,  0.0041, -0.0877,  0.2176, -0.7063,
          0.0041, -0.0877,  0.2176, -0.7063]])

- 拼接Tensor【torch.stack】

In [12]:
t3 = torch.stack([tensor,tensor,tensor],dim=0)
t3

tensor([[[ 0.4111, -0.2422,  1.0655,  0.1739],
         [ 0.0115, -0.1728,  0.7108, -0.3837],
         [-0.0645, -0.9171,  0.5292,  2.6154],
         [ 0.0041, -0.0877,  0.2176, -0.7063]],

        [[ 0.4111, -0.2422,  1.0655,  0.1739],
         [ 0.0115, -0.1728,  0.7108, -0.3837],
         [-0.0645, -0.9171,  0.5292,  2.6154],
         [ 0.0041, -0.0877,  0.2176, -0.7063]],

        [[ 0.4111, -0.2422,  1.0655,  0.1739],
         [ 0.0115, -0.1728,  0.7108, -0.3837],
         [-0.0645, -0.9171,  0.5292,  2.6154],
         [ 0.0041, -0.0877,  0.2176, -0.7063]]])

In [13]:
t4 = torch.stack([tensor,tensor,tensor], dim=1)
t4

tensor([[[ 0.4111, -0.2422,  1.0655,  0.1739],
         [ 0.4111, -0.2422,  1.0655,  0.1739],
         [ 0.4111, -0.2422,  1.0655,  0.1739]],

        [[ 0.0115, -0.1728,  0.7108, -0.3837],
         [ 0.0115, -0.1728,  0.7108, -0.3837],
         [ 0.0115, -0.1728,  0.7108, -0.3837]],

        [[-0.0645, -0.9171,  0.5292,  2.6154],
         [-0.0645, -0.9171,  0.5292,  2.6154],
         [-0.0645, -0.9171,  0.5292,  2.6154]],

        [[ 0.0041, -0.0877,  0.2176, -0.7063],
         [ 0.0041, -0.0877,  0.2176, -0.7063],
         [ 0.0041, -0.0877,  0.2176, -0.7063]]])

- 算术运算

In [14]:
tensor = torch.ones(4, 4)
y1 = tensor @ tensor.T  # @表示矩阵相乘
print(y1)

y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(y1)
print(y3)

torch.matmul(tensor, tensor, out=y3)
print(y3)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[0.3325, 0.8416, 0.6547, 0.8515],
        [0.3425, 0.5713, 0.6465, 0.7765],
        [0.8757, 0.2135, 0.4122, 0.0457],
        [0.0416, 0.9093, 0.9559, 0.0958]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [15]:
z1 = tensor * tensor  # *表示矩阵对应的元素相乘
print(z1)

z2 = tensor.mul(tensor)
print(z2)

z3 = torch.rand_like(tensor)
print(z3)

torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.1996, 0.1459, 0.6190, 0.9285],
        [0.1306, 0.6519, 0.0376, 0.6435],
        [0.5515, 0.3206, 0.5962, 0.4161],
        [0.5303, 0.5918, 0.7641, 0.6044]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


- 单元素Tensor

In [16]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
agg = tensor.sum()
agg

tensor(16.)

In [18]:
agg_item = agg.item()  # 将Tensor的值以Python标准数据类型返回【只支持单元素Tensor，多元素Tensor应用tolist()】
print(agg_item, type(agg_item))

16.0 <class 'float'>


- 就地操作【函数名以_结尾，如copy_()，add_()】

In [19]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
tensor.add_(5)

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])