# 学习 PyTorch-Day1


In [1]:
import torch
import numpy as np

# 指认到M1芯片
# device = torch.device("mps")

# 指认到CUDA
device = torch.device("cuda")

## 初始化一个 Tensor


- 直接从数据初始化


In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

- 直接从 Numpy 数组转换


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

- 从另一个 Tensor 转换(将会与该 Tensor 在 shape 以及 datatype 上保持一致)


In [4]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)  # 使用x_data的shape，被重新给定了datashape(float)
x_rand

tensor([[0.9870, 0.5813],
        [0.5893, 0.6065]])

- 使用一个随机量或者一个常量

In [6]:
shape = (2, 3)  # 表示Tensor的维度信息

rand_tensor = torch.rand(shape)  # 使用给定shape初始化一个Tensor，值全为1
print(rand_tensor)

ones_tensor = torch.ones(shape)  # 使用给定shape初始化一个Tensor，值全部随机
print(ones_tensor)

zeros_tensor = torch.zeros(shape)  # 使用给定shape初始化一个Tensor，值全为0
print(zeros_tensor)

tensor([[0.6183, 0.9107, 0.7262],
        [0.7252, 0.0896, 0.4870]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor的属性

Tensor的属性包括且不限于如下：

1. shape 【尺寸】
2. dtype 【数据类型】
3. device 【存储设备】

In [7]:
t = torch.rand(3, 4, device=device)
print("Shape of tensor: {}".format(t.shape))
print("Datatype of tensor: {}".format(t.dtype))
print("Device of tensor: {}".format(t.device))

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cuda:0


## Tensor 运算

- to method

In [8]:
# Tensor默认是分配在CPU上，如果我们有GPU可以使用，应该使用 to 方法将Tensor转到GPU上
# if torch.cuda.is_available():
tensor = torch.rand((3,2))
if torch.backends.mps.is_available():
    tensor = tensor.to("mps")
tensor

tensor([[0.5709, 0.1789],
        [0.0252, 0.8045],
        [0.8686, 0.5614]])

- 类似于Numpy的索引和切片

In [9]:
tensor = torch.randn(4, 4)
print(tensor)
print("First row of tensor: {}".format(tensor[0]))
print("First column of tensor: {}".format(tensor[:, 0]))
print("last column of tensor: {}".format(tensor[:, -1]))

tensor([[-0.3693, -1.1022, -0.5517, -0.1278],
        [ 2.2797,  1.1478, -2.0291, -0.6513],
        [ 1.0212,  0.4801, -0.0126, -0.2516],
        [-0.5847,  0.3660,  0.7753, -0.9736]])
First row of tensor: tensor([-0.3693, -1.1022, -0.5517, -0.1278])
First column of tensor: tensor([-0.3693,  2.2797,  1.0212, -0.5847])
last column of tensor: tensor([-0.1278, -0.6513, -0.2516, -0.9736])


- 拼接Tensor【torch.cat】

In [10]:
t1 = torch.cat([tensor,tensor,tensor], dim=0)
t1

tensor([[-0.3693, -1.1022, -0.5517, -0.1278],
        [ 2.2797,  1.1478, -2.0291, -0.6513],
        [ 1.0212,  0.4801, -0.0126, -0.2516],
        [-0.5847,  0.3660,  0.7753, -0.9736],
        [-0.3693, -1.1022, -0.5517, -0.1278],
        [ 2.2797,  1.1478, -2.0291, -0.6513],
        [ 1.0212,  0.4801, -0.0126, -0.2516],
        [-0.5847,  0.3660,  0.7753, -0.9736],
        [-0.3693, -1.1022, -0.5517, -0.1278],
        [ 2.2797,  1.1478, -2.0291, -0.6513],
        [ 1.0212,  0.4801, -0.0126, -0.2516],
        [-0.5847,  0.3660,  0.7753, -0.9736]])

In [11]:
t2 = torch.cat([tensor,tensor,tensor], dim=1)
t2

tensor([[-0.3693, -1.1022, -0.5517, -0.1278, -0.3693, -1.1022, -0.5517, -0.1278,
         -0.3693, -1.1022, -0.5517, -0.1278],
        [ 2.2797,  1.1478, -2.0291, -0.6513,  2.2797,  1.1478, -2.0291, -0.6513,
          2.2797,  1.1478, -2.0291, -0.6513],
        [ 1.0212,  0.4801, -0.0126, -0.2516,  1.0212,  0.4801, -0.0126, -0.2516,
          1.0212,  0.4801, -0.0126, -0.2516],
        [-0.5847,  0.3660,  0.7753, -0.9736, -0.5847,  0.3660,  0.7753, -0.9736,
         -0.5847,  0.3660,  0.7753, -0.9736]])

- 拼接Tensor【torch.stack】

In [12]:
t3 = torch.stack([tensor,tensor,tensor],dim=0)
t3

tensor([[[-0.3693, -1.1022, -0.5517, -0.1278],
         [ 2.2797,  1.1478, -2.0291, -0.6513],
         [ 1.0212,  0.4801, -0.0126, -0.2516],
         [-0.5847,  0.3660,  0.7753, -0.9736]],

        [[-0.3693, -1.1022, -0.5517, -0.1278],
         [ 2.2797,  1.1478, -2.0291, -0.6513],
         [ 1.0212,  0.4801, -0.0126, -0.2516],
         [-0.5847,  0.3660,  0.7753, -0.9736]],

        [[-0.3693, -1.1022, -0.5517, -0.1278],
         [ 2.2797,  1.1478, -2.0291, -0.6513],
         [ 1.0212,  0.4801, -0.0126, -0.2516],
         [-0.5847,  0.3660,  0.7753, -0.9736]]])

In [13]:
t4 = torch.stack([tensor,tensor,tensor], dim=1)
t4

tensor([[[-0.3693, -1.1022, -0.5517, -0.1278],
         [-0.3693, -1.1022, -0.5517, -0.1278],
         [-0.3693, -1.1022, -0.5517, -0.1278]],

        [[ 2.2797,  1.1478, -2.0291, -0.6513],
         [ 2.2797,  1.1478, -2.0291, -0.6513],
         [ 2.2797,  1.1478, -2.0291, -0.6513]],

        [[ 1.0212,  0.4801, -0.0126, -0.2516],
         [ 1.0212,  0.4801, -0.0126, -0.2516],
         [ 1.0212,  0.4801, -0.0126, -0.2516]],

        [[-0.5847,  0.3660,  0.7753, -0.9736],
         [-0.5847,  0.3660,  0.7753, -0.9736],
         [-0.5847,  0.3660,  0.7753, -0.9736]]])

- 算术运算

In [14]:
tensor = torch.ones(4, 4)
y1 = tensor @ tensor.T  # @表示矩阵相乘
print(y1)

y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(y1)
print(y3)

torch.matmul(tensor, tensor, out=y3)
print(y3)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[0.4941, 0.2910, 0.3898, 0.0980],
        [0.3838, 0.1652, 0.8461, 0.9115],
        [0.7712, 0.4864, 0.2991, 0.6117],
        [0.6081, 0.0538, 0.9752, 0.3425]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [15]:
z1 = tensor * tensor  # *表示矩阵对应的元素相乘
print(z1)

z2 = tensor.mul(tensor)
print(z2)

z3 = torch.rand_like(tensor)
print(z3)

torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.9615, 0.8311, 0.5907, 0.7283],
        [0.3731, 0.0103, 0.3927, 0.1522],
        [0.3298, 0.6552, 0.5003, 0.0296],
        [0.1078, 0.0631, 0.5580, 0.1643]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


- 单元素Tensor

In [16]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
agg = tensor.sum()
agg

tensor(16.)

In [18]:
agg_item = agg.item()  # 将Tensor的值以Python标准数据类型返回【只支持单元素Tensor，多元素Tensor应用tolist()】
print(agg_item, type(agg_item))

16.0 <class 'float'>


- 就地操作【函数名以_结尾，如copy_()，add_()】

In [19]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
tensor.add_(5)

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

## Bridge with Numpy

- CPU上的Tensor可以与Numpy数组共享底层内存，改变其中一个即可改变另一个

### Tensor 转成 Numpy 数组

In [21]:
t = torch.ones(5)
n = t.numpy()
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [22]:
# 改变Tensor，观察Numpy数组是否变化
t.add_(2)
print(t)
print(n)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


### Numpy数组 转成 Tensor

In [23]:
n = np.ones(5)
t = torch.from_numpy(n)
print(n)
print(t)

# 修改Numpy数组，观察Tensor是否变化
np.add(n, 3, out=n)
print(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[4. 4. 4. 4. 4.]
tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
