# 学习 PyTorch-Day1


In [1]:
import torch
import numpy as np

# 指认到M1芯片
device = torch.device("mps")

## 初始化一个 Tensor


- 直接从数据初始化


In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

- 直接从 Numpy 数组转换


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

- 从另一个 Tensor 转换(将会与该 Tensor 在 shape 以及 datatype 上保持一致)


In [4]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)  # 使用x_data的shape，被重新给定了datashape(float)
x_rand

tensor([[0.9166, 0.8740],
        [0.2459, 0.2191]])

- 使用一个随机量或者一个常量

In [6]:
shape = (2, 3)  # 表示Tensor的维度信息

rand_tensor = torch.rand(shape)  # 使用给定shape初始化一个Tensor，值全为1
print(rand_tensor)

ones_tensor = torch.ones(shape)  # 使用给定shape初始化一个Tensor，值全部随机
print(ones_tensor)

zeros_tensor = torch.zeros(shape)  # 使用给定shape初始化一个Tensor，值全为0
print(zeros_tensor)

tensor([[0.1557, 0.7070, 0.5393],
        [0.8809, 0.9653, 0.4368]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor的属性

Tensor的属性包括且不限于如下：

1. shape 【尺寸】
2. dtype 【数据类型】
3. device 【存储设备】

In [7]:
t = torch.rand(3, 4, device=device)
print("Shape of tensor: {}".format(t.shape))
print("Datatype of tensor: {}".format(t.dtype))
print("Device of tensor: {}".format(t.device))

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: mps:0


## Tensor 运算

- to method

In [8]:
# Tensor默认是分配在CPU上，如果我们有GPU可以使用，应该使用 to 方法将Tensor转到GPU上
# if torch.cuda.is_available():
tensor = torch.rand((3,2))
if torch.backends.mps.is_available():
    tensor = tensor.to("mps")
tensor

/opt/anaconda3/envs/ml/lib/python3.7/site-packages/torch/_tensor_str.py:103: UserWarning: The operator 'aten::bitwise_and.Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484744261/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))


tensor([[0.1509, 0.3758],
        [0.1715, 0.0273],
        [0.2087, 0.5087]], device='mps:0')

- 类似于Numpy的索引和切片

In [9]:
tensor = torch.randn(4, 4)
print(tensor)
print("First row of tensor: {}".format(tensor[0]))
print("First column of tensor: {}".format(tensor[:, 0]))
print("last column of tensor: {}".format(tensor[:, -1]))

tensor([[-0.5812, -0.6559, -1.5222, -0.4646],
        [ 0.6380,  1.0359, -0.0823,  0.4162],
        [-0.7995, -1.0322, -0.6656,  0.4280],
        [ 0.3517,  1.4000, -0.2979,  1.9109]])
First row of tensor: tensor([-0.5812, -0.6559, -1.5222, -0.4646])
First column of tensor: tensor([-0.5812,  0.6380, -0.7995,  0.3517])
last column of tensor: tensor([-0.4646,  0.4162,  0.4280,  1.9109])


- 拼接Tensor【torch.cat】

In [10]:
t1 = torch.cat([tensor,tensor,tensor], dim=0)
t1

tensor([[-0.5812, -0.6559, -1.5222, -0.4646],
        [ 0.6380,  1.0359, -0.0823,  0.4162],
        [-0.7995, -1.0322, -0.6656,  0.4280],
        [ 0.3517,  1.4000, -0.2979,  1.9109],
        [-0.5812, -0.6559, -1.5222, -0.4646],
        [ 0.6380,  1.0359, -0.0823,  0.4162],
        [-0.7995, -1.0322, -0.6656,  0.4280],
        [ 0.3517,  1.4000, -0.2979,  1.9109],
        [-0.5812, -0.6559, -1.5222, -0.4646],
        [ 0.6380,  1.0359, -0.0823,  0.4162],
        [-0.7995, -1.0322, -0.6656,  0.4280],
        [ 0.3517,  1.4000, -0.2979,  1.9109]])

In [11]:
t2 = torch.cat([tensor,tensor,tensor], dim=1)
t2

tensor([[-0.5812, -0.6559, -1.5222, -0.4646, -0.5812, -0.6559, -1.5222, -0.4646,
         -0.5812, -0.6559, -1.5222, -0.4646],
        [ 0.6380,  1.0359, -0.0823,  0.4162,  0.6380,  1.0359, -0.0823,  0.4162,
          0.6380,  1.0359, -0.0823,  0.4162],
        [-0.7995, -1.0322, -0.6656,  0.4280, -0.7995, -1.0322, -0.6656,  0.4280,
         -0.7995, -1.0322, -0.6656,  0.4280],
        [ 0.3517,  1.4000, -0.2979,  1.9109,  0.3517,  1.4000, -0.2979,  1.9109,
          0.3517,  1.4000, -0.2979,  1.9109]])

- 拼接Tensor【torch.stack】

In [12]:
t3 = torch.stack([tensor,tensor,tensor],dim=0)
t3

tensor([[[-0.5812, -0.6559, -1.5222, -0.4646],
         [ 0.6380,  1.0359, -0.0823,  0.4162],
         [-0.7995, -1.0322, -0.6656,  0.4280],
         [ 0.3517,  1.4000, -0.2979,  1.9109]],

        [[-0.5812, -0.6559, -1.5222, -0.4646],
         [ 0.6380,  1.0359, -0.0823,  0.4162],
         [-0.7995, -1.0322, -0.6656,  0.4280],
         [ 0.3517,  1.4000, -0.2979,  1.9109]],

        [[-0.5812, -0.6559, -1.5222, -0.4646],
         [ 0.6380,  1.0359, -0.0823,  0.4162],
         [-0.7995, -1.0322, -0.6656,  0.4280],
         [ 0.3517,  1.4000, -0.2979,  1.9109]]])

In [13]:
t4 = torch.stack([tensor,tensor,tensor], dim=1)
t4

tensor([[[-0.5812, -0.6559, -1.5222, -0.4646],
         [-0.5812, -0.6559, -1.5222, -0.4646],
         [-0.5812, -0.6559, -1.5222, -0.4646]],

        [[ 0.6380,  1.0359, -0.0823,  0.4162],
         [ 0.6380,  1.0359, -0.0823,  0.4162],
         [ 0.6380,  1.0359, -0.0823,  0.4162]],

        [[-0.7995, -1.0322, -0.6656,  0.4280],
         [-0.7995, -1.0322, -0.6656,  0.4280],
         [-0.7995, -1.0322, -0.6656,  0.4280]],

        [[ 0.3517,  1.4000, -0.2979,  1.9109],
         [ 0.3517,  1.4000, -0.2979,  1.9109],
         [ 0.3517,  1.4000, -0.2979,  1.9109]]])

- 算术运算

In [14]:
tensor = torch.ones(4, 4)
y1 = tensor @ tensor.T  # @表示矩阵相乘
print(y1)

y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(y1)
print(y3)

torch.matmul(tensor, tensor, out=y3)
print(y3)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[5.5371e-01, 3.6530e-01, 7.3108e-01, 9.8381e-01],
        [5.1491e-01, 7.4635e-01, 8.1365e-01, 3.5566e-01],
        [3.9448e-01, 2.5862e-04, 4.0564e-01, 3.7819e-01],
        [8.5189e-01, 8.7781e-01, 2.8200e-01, 8.0823e-01]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [15]:
z1 = tensor * tensor  # *表示矩阵对应的元素相乘
print(z1)

z2 = tensor.mul(tensor)
print(z2)

z3 = torch.rand_like(tensor)
print(z3)

torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.8143, 0.2839, 0.7133, 0.3796],
        [0.4632, 0.2482, 0.2102, 0.9525],
        [0.9346, 0.4250, 0.0906, 0.6663],
        [0.3400, 0.9633, 0.6378, 0.8279]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


- 单元素Tensor

In [16]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
agg = tensor.sum()
agg

tensor(16.)

In [18]:
agg_item = agg.item()  # 将Tensor的值以Python标准数据类型返回【只支持单元素Tensor，多元素Tensor应用tolist()】
print(agg_item, type(agg_item))

16.0 <class 'float'>


- 就地操作【函数名以_结尾，如copy_()，add_()】

In [19]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
tensor.add_(5)

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])